package vn.ca.vietvoiceoffline;
import android.content.*;import android.graphics.*;import android.os.Build;import android.provider.Settings;import android.view.*;
final class RegionPicker extends View {
 private static RegionPicker shown;static volatile boolean active;static volatile int revision;
 private final WindowManager wm;private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private Rect selection;private float downX,downY;private boolean dragging;private int screenW,screenH;private final float d;
 static void show(Context c){if(!Settings.canDrawOverlays(c)){State.status("Cần quyền hiển thị trên ứng dụng khác để khoanh vùng.");return;}closePicker();RegionPicker p=new RegionPicker(c.getApplicationContext());WindowManager.LayoutParams a=new WindowManager.LayoutParams(-1,-1,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);a.gravity=Gravity.TOP|Gravity.LEFT;if(Build.VERSION.SDK_INT>=28)a.layoutInDisplayCutoutMode=WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;try{p.wm.addView(p,a);shown=p;active=true;revision++;}catch(Exception e){State.status("Không mở được vùng chọn: "+State.error(e));}}
 static void closePicker(){RegionPicker p=shown;shown=null;active=false;if(p!=null)try{p.wm.removeView(p);}catch(Exception ignored){}}
 private RegionPicker(Context c){super(c);wm=c.getSystemService(WindowManager.class);d=getResources().getDisplayMetrics().density;}
 @Override protected void onSizeChanged(int w,int h,int ow,int oh){super.onSizeChanged(w,h,ow,oh);android.util.DisplayMetrics m=new android.util.DisplayMetrics();wm.getDefaultDisplay().getRealMetrics(m);screenW=m.widthPixels;screenH=m.heightPixels;Rect r=SubtitleRegion.get(getContext(),screenW,screenH);int[] at=new int[2];getLocationOnScreen(at);r.offset(-at[0],-at[1]);selection=r;}
 @Override protected void onDraw(Canvas c){super.onDraw(c);if(selection==null)return;paint.setColor(0x77000000);c.drawRect(0,0,getWidth(),selection.top,paint);c.drawRect(0,selection.bottom,getWidth(),getHeight(),paint);c.drawRect(0,selection.top,selection.left,selection.bottom,paint);c.drawRect(selection.right,selection.top,getWidth(),selection.bottom,paint);paint.setColor(0xff37E7C6);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(3*d);c.drawRect(selection,paint);paint.setStyle(Paint.Style.FILL);paint.setColor(0xee102D37);c.drawRect(0,24*d,getWidth(),125*d,paint);paint.setColor(Color.WHITE);paint.setTextSize(15*d);c.drawText("Kéo khoanh sát phần phụ đề",12*d,51*d,paint);paint.setColor(0xff37E7C6);c.drawText("Dùng vùng này",12*d,96*d,paint);paint.setColor(Color.WHITE);c.drawText("Hủy",getWidth()*.76f,96*d,paint);}
 @Override public boolean onTouchEvent(MotionEvent e){float x=Math.max(0,Math.min(getWidth(),e.getX())),y=Math.max(0,Math.min(getHeight(),e.getY()));if(e.getAction()==MotionEvent.ACTION_DOWN){if(y>=65*d&&y<=125*d){if(x<getWidth()*.65f)save();else closePicker();return true;}dragging=true;downX=x;downY=y;return true;}if(dragging&&(e.getAction()==MotionEvent.ACTION_MOVE||e.getAction()==MotionEvent.ACTION_UP)){selection=new Rect((int)Math.min(x,downX),(int)Math.min(y,downY),(int)Math.max(x,downX),(int)Math.max(y,downY));invalidate();if(e.getAction()==MotionEvent.ACTION_UP){dragging=false;performClick();}return true;}if(e.getAction()==MotionEvent.ACTION_CANCEL)dragging=false;return true;}
 @Override public boolean performClick(){super.performClick();return true;}
 private void save(){if(selection==null||selection.width()<40*d||selection.height()<16*d){State.status("Vùng quá nhỏ. Kéo khoanh lại phần chữ.");return;}int[] at=new int[2];getLocationOnScreen(at);Rect r=new Rect(selection);r.offset(at[0],at[1]);if(!r.intersect(0,0,screenW,screenH))return;SubtitleRegion.save(getContext(),r,screenW,screenH);revision++;closePicker();State.status("Đã lưu vùng phụ đề. Đặt bảng dịch nổi ngoài vùng chữ.");}
}
